name: 'Release'

on:
  push:
    branches:
      - main
      - master
      - feat/multi-domain-support # TODO: Remove this once merged

jobs:
  release:
    name: Publish release if new version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - posthog-react-native
          - posthog-node
          - posthog-web

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check package version and detect an update
        id: check-package-version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ matrix.package }}

      - name: Set up Node 14
        uses: actions/setup-node@v2
        if: steps.check-package-version.outputs.is-new-version == 'true'
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        if: steps.check-package-version.outputs.is-new-version == 'true'
        run: yarn --frozen-lockfile

      - name: Build
        if: steps.check-package-version.outputs.is-new-version == 'true'
        run: yarn build

      - name: Publish the package in the npm registry
        if: steps.check-package-version.outputs.is-new-version == 'true'
        working-directory: ${{ matrix.package }}
        run: npm publish --access public --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        if: steps.check-package-version.outputs.is-new-version == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package }}-v${{ steps.check-package-version.outputs.committed-version }}
          release_name: ${{ matrix.package }}-${{ steps.check-package-version.outputs.committed-version }}
