name: 'Release'

on:
  push:
    branches:
      - main
      - master
      - feat/multi-domain-support

jobs:
  check-package-version:
    strategy:
      matrix:
        package: [posthog-react-native, posthog-node, posthog-web]
    name: Check package version and detect an update
    runs-on: ubuntu-latest
    outputs:
      committed-version: ${{ steps.check-package-version.outputs.committed-version }}
      published-version: ${{ steps.check-package-version.outputs.published-version }}
      is-new-version: ${{ steps.check-package-version.outputs.is-new-version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check package version and detect an update
        id: check-package-version
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ matrix.package }}

  release:
    name: Publish release if new version
    runs-on: ubuntu-latest
    needs: check-package-version
    strategy:
      matrix: ${{fromJson(needs.check-package-version.outputs)}}
    if: matrix.is-new-version == 'true'
    env:
      COMMITTED_VERSION: ${{ matrix.committed-version }}
      PUBLISHED_VERSION: ${{ matrix.published-version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish the package in the npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_NOT }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.COMMITTED_VERSION }}
          release_name: ${{ env.COMMITTED_VERSION }}
