name: Unit Tests

on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm test
